name: 'Setup Project Environment'
description: 'Setup Node.js, install dependencies and checkout code'

inputs:
  fetch_depth:
    description: 'Git fetch depth (0 for full history)'
    required: false
    default: '1'
  node_version:
    description: 'Node.js version'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch_depth }}

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install dependencies
      run: npm ci
