name: Manual Dev Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to dev'
        required: true
        default: 'main'
        type: string

jobs:
  manual-dev-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build dev project
        run: npm run build:dev
        env:
          AIUTA_IFRAME_BRANCH: ${{ inputs.branch }}

      # Authenticate with GCP
      - name: Set up GCP credentials Dev
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_STATIC_UPLOADER_SA_KEY_JSON_DEV }}

      # Upload dist/ to GCS
      - name: Upload to GCS bucket Dev JS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist/sdk/
          destination: aiuta_dev_static/sdk/${{ inputs.branch }}/
          parent: false
          process_gcloudignore: 'false'

      # Upload dist/ to GCS
      - name: Upload to GCS bucket Dev Iframe
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist/iframe/
          destination: aiuta_dev_static/sdk/${{ inputs.branch }}/
          parent: false
          process_gcloudignore: 'false'

      - name: Deployment Summary
        run: |
          echo "✅ Dev deployment completed successfully!"
          echo "📦 Branch: ${{ inputs.branch }}"
          echo "📁 Uploaded to: aiuta_dev_static/sdk/${{ inputs.branch }}/"
          echo ""
          echo "🔗 Files available at:"
          echo ""
          for file in dist/sdk/*; do
            filename=$(basename "$file")
            echo "- https://static.dev.aiuta.com/sdk/${{ inputs.branch }}/${filename}"
          done
