name: Build and Deploy Preprod on Main

on:
  push:
    branches: [main]

jobs:
  build-and-deploy-preprod:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build preprod project
        run: npm run build:preprod

      # Authenticate with GCP
      - name: Set up GCP credentials Preprod
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_STATIC_UPLOADER_SA_KEY_JSON_PREPROD }}

      # Upload dist/ to GCS
      - name: Upload to GCS bucket Preprod JS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist/sdk/
          destination: aiuta_preprod_static/sdk/main/
          parent: false
          process_gcloudignore: 'false'

      # Upload dist/ to GCS
      - name: Upload to GCS bucket Preprod Iframe
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist/iframe/
          destination: aiuta_preprod_static/sdk/main/
          parent: false
          process_gcloudignore: 'false'

      - name: Deployment Summary
        run: |
          echo "✅ Preprod deployment completed successfully!"
          echo "📦 Branch: main"
          echo "📁 Uploaded to: aiuta_preprod_static/sdk/main/"
          echo ""
          echo "🔗 Files available at:"
          echo ""
          for file in dist/sdk/*; do
            filename=$(basename "$file")
            echo "- https://static.preprod.aiuta.com/sdk/main/${filename}"
          done
