name: Build & Release Artifacts

on:
  push:
    tags:
      - 'v*' # Trigger only when pushing version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust if needed
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive build output
        run: |
          cd dist
          zip -r ../release.zip .

      # Authenticate with GCP
      - name: Set up GCP credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_STATIC_UPLOADER_SA_KEY }}

      # Upload dist/ to GCS
      - name: Upload to GCS bucket
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: dist/
          destination: aiuta_dev_static/sdk/${{ github.ref_name }}/
          parent: false

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release.zip

