name: Build & Release Artifacts

on:
  push:
    tags:
      - 'v*' # Trigger only when pushing version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust if needed
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive build output
        run: |
          cd dist
          zip -r ../release.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
